//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int IdUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryPhone { get; set; }
        public string DeliveryEmail { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public string Updated_by { get; set; }
        public int Status { get; set; }
    }
}
