//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string Image { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ShortDes { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string FullDecription { get; set; }
        public double Price { get; set; }
        public string Position { get; set; }
        public Nullable<double> PriceSale { get; set; }
        public Nullable<int> HotSale { get; set; }
        public Nullable<int> DealOfWeek { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string UploadBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public int Status { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpLoad { get; set; }
    }
}
